# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e0f1e97ad69f3db7ca3b255b62a58cc33a1e42262d456ceebe87348090ee60dfbbf1380afcba9b837321e867384cce2c317164d772f59fda502b58d18b20cb7

test:
  secret_key_base: df94dab138928d49b2df4a2f1451f1d86a1ab590f57e4c1706321727711c6bfc49b87a3da715b3e4a5d8542d9dc916217545f4ac1d195c0f499cf7147aa1de5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
